spring.application.name=desafio-mercado-livre

# RabbitMQ
spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USER:admin}
spring.rabbitmq.password=${RABBITMQ_PASS:changeme}

# Active Profile (dev, test, prod)
spring.profiles.active=prod

# JWT Configuration
# jwt.secret=${JWT_SECRET}
# jwt.issuer=${JWT_ISSUER}